STEVE (Simultaneous Thread EValuation of gEant4): simulation Namespace Reference
simulation Namespace Reference
Functions
int bash (std::string command, int nice=0)
Call the given command in bash.
std::string ReplaceString (std::string subject, const std::string &search, const std::string &replace)
Replace all instances of a string in another string with a third string.
bool directoryContains (string dir)
Check current directory contains the string provided/.
void regexReplace (string &input, const string threadnumber="")
Apply regex transformations to input string.
void runSimRegex (string regex, string num)
Run a thread of the simulation.
bool clean (bool autoClean, string cleanCMD="rm -f *.root;")
Clean the current directory.
int runSim (string regex, string numSims="48", string output="g4out.root", string cleanCMD="rm -f *.root", bool autoClean=0, bool afterClean=0)
Runs the multithreading workaround. Exists so that it can be easily called from another program.
Function Documentation
int simulation::bash (std::string command, int nice = 0)
Call the given command in bash.
Call the given command in bash
Arguments
std::string command - Command to run. Note that non-interpreters wrappers like nice may not work with aliased commands.
int nice - nice value to run command at (added to avoid issues with nice not working with aliases). Defualts to zero.
Returns the return value of the given function
Referenced by clean(), runSim(), and runSimRegex().
bool simulation::clean (bool autoClean, string cleanCMD = "rm -f *.root;")
Clean the current directory.
Clean the current directory
Arguments:
bool autoClean - Bool of whether or not to automatically clean the directory. It defualts to zero, which will prompt the user first, but if set to one the program cleans the directory without outside input.
string cleanCMD - Sh (bourne shell) command used to clean directory. Defaults to rm -f *.root.
Notes:
Ensures there are no files matching g4out*.root in the current directory. If there are, it offers to automatically remove them, or to exit the program to allow the user to save and remove them manually. Also note that this assumes that all output files end in .root, and no other files end in .root. If you want to preserve these files, you should move them to a differnt directory or change their filename (as an example, g4out.root->g4out.root.keep).
Referenced by runSim().
bool simulation::directoryContains (string dir)
Check current directory contains the string provided/.
Check current directory contains the string provided/
Arguments:
string dir - Directory to check if contained
Notes:
If it is, it returns zero, otherwise it prompts the user if they want to procede anyway or not. Returns 0 if they want to procede and 1 otherwise.
Referenced by main().
void simulation::regexReplace (string & input, const string threadnumber = "")
Apply regex transformations to input string.
Apply regex transformations to input string.
Arguments:
string& input - Input string reference to modify in place.
const string threadnumber - Threadnumber string to replace n with. Only valid for threads, so it defaults to "".
Transformations:
"%d" -> date
"%t" -> time
"%u" -> unix time
"%n" -> thread number
Referenced by runSim(), and runSimRegex().
std::string simulation::ReplaceString (std::string subject, const std::string & search, const std::string & replace)
Replace all instances of a string in another string with a third string.
Replace all instances of a string in another string with a third string. Credit to Czarek Tomczak on stack overflow for supplying the code in response to a question asked by NullVoxPopuli.
Arguments:
std::string subject - String to do replacements in.
const std::string& search - Substring to replace with the replace string.
const std::string& replace - Substring to replace the search string with.
Referenced by regexReplace().
int simulation::runSim (string regex, string numSims = "48", string output = "g4out.root", string cleanCMD = "rm -f *.root", bool autoClean = 0, bool afterClean = 0)
Runs the multithreading workaround. Exists so that it can be easily called from another program.
Runs the multithreading workaround. Exists so that it can be easily called from another program.
Arguments:
string regex - Runs the simulation from the string provided once all instances of "%n" are replaced by the thread number. It allows for more flexibility in command execution as the singlethreaded command for any simulation (that has the two modifications described below) can easily be multithreaded. Make sure to redirect stdout and stderr to a file or /dev/null to prevent simultaneous writing to the console. Note that the string should be surrounded in quotes as to not specify additional arguments.
string numSims - Number of threads to run. Defaults to 48.
string output - Final combined output .root filename. Defaults to g4out.root.
string cleanCMD - Supply your own clean command (bourne shell only). If not included, default clean command is rm -f *.root. This can reference a file if the command executes a file.
bool autoClean - Automatically cleans directory and skips directory check without user input.
bool afterclean - Cleans directory after simulation completion by adding .keep to the end of the output file, then running the clean function, which is by defailt rm -f *.root, then moving the output back to the original filename.
Referenced by main().
void simulation::runSimRegex (string regex, string num)
Run a thread of the simulation.
Run a thread of the simulation
Arguments:
string regex - Command to run for each string, where every instance of "%n" will be replaced with the thread number.
string num - Thread number
Referenced by runSim().