STEVE (Simultaneous Thread EValuation of gEant4): runSim2.0.cpp File Reference
runSim2.0.cpp File Reference
#include <string>
#include <iostream>
#include <thread>
#include <vector>
#include <mutex>
#include <ctime>
Functions
std::string ReplaceString (std::string subject, const std::string &search, const std::string &replace)
void regexReplace (string &input, const string threadnumber="")
void runSimRegex (string regex, string num)
bool clean (bool autoClean=0)
int main (int argc, char **argv)
Variables
mutex printing
To prevent multiple threads from using stdout at the same time.
Function Documentation
bool clean (bool autoClean = 0)
Clean the current directory
Arguments:
bool autoClean - Bool of whether or not to automatically clean the directory. It defualts to zero, which will prompt the user first, but if set to one the program cleans the directory without outside input.
Notes:
Ensures there are no files matching g4out*.root in the current directory. If there are, it offers to automatically remove them, or to exit the program to allow the user to save and remove them manually. Also note that this assumes that all output files end in .root, and no other files end in .root. If you want to preserve these files, you should move them to a differnt directory or change their filename (as an example, g4out.root->g4out.root.keep).
Referenced by main().
int main (int argc, char ** argv)
Multithreading workaround
Arguments:
-t threads - Number of threads to run
-y - Automatically cleans directory without user input.
--clean - Automatically cleans directory after simulation completion, leaving only the combined output file instead of the induvidual .root files from each thread. Note, this removes all .root files except for the final output file, so do not use if you wish to preserve other .root files in the directory. Instead, with knowledge of how your induvidual thread files are named, run an rm command after runSim.o to clean up.
--regex - Runs the simulation from the string provided once all instances of "%n" are replaced by the thread number. It allows for more flexibility in command execution as the singlethreaded command for any simulation (that has the two modifications described below) can easily be multithreaded. Make sure to redirect stdout and stderr to a file or /dev/null to prevent simultaneous writing to the console. Note that the string should be surrounded in quotes as to not specify additional arguments.
--output - Final combined output .root filename. Defaults to g4out.root.
--test - Internal testing flag. Currently unused.
Notes:
Changes needed in simulation for runSim to work:
Simulation seed must pull from /dev/random Reference implementation:
#include <fstream>
G4int random_seed(){ // Credit to posop on stackoverflow for code that I adapted. Reading an int from /dev/random is a better random seed than time(NULL) because it is cryptographically secure and protects against multiple instances loading in same second, which was a problem before.
    G4int seed;
    std::ifstream file("/dev/random",std::ios::binary);
    if(file.is_open()){
        char *memblock;
        G4int size=sizeof(G4int);
        memblock=new char [size];
        file.read(memblock,size);
        file.close();
        seed=*reinterpret_cast<G4int*>(memblock);
        delete[] memblock;
        return seed;
    }else{return random_seed();} // Continually retry until /dev/random is free
}
Then in int main
G4int seed = random_seed();
G4Random::setTheSeed(seed);
Simulation must take an argument to change output filename by adding characters (eg. adding the supplied string between the g4out and the .root). Note that the resulting files must still end in .root. Reference implmentation:
// In main executable, eg. Griffinv10.cc
// In global scope:
G4String file_name="";
// In argument parsing:
if(argc>2) file_name=argv[2];
// In Histomanager.cc
// In HistoManager::HistoManager()
// Replacing fFileName[0] = "g4out";
extern G4String file_name;
fFileName[0] = "g4out"+file_name;
Building
To build runSim.cpp, use
g++ -Wall -std=c++11 -pthread -Ofast -o runSim.o runSim.cpp
void regexReplace (string & input, const string threadnumber = "")
Apply regex transformations to input string.
Arguments:
string& input - Input string reference to modify in place.
const string threadnumber - Threadnumber string to replace n with. Only valid for threads, so it defaults to "".
Transformations:
"%d" -> date
"%t" -> time
"%u" -> unix time
"%n" -> thread number
Referenced by main(), and runSimRegex().
std::string ReplaceString (std::string subject, const std::string & search, const std::string & replace)
Replace all instances of a string in another string with a third string. Credit to Czarek Tomczak on stack overflow for supplying the code in response to a question asked by NullVoxPopuli.
Referenced by regexReplace().
void runSimRegex (string regex, string num)
Run a thread of the simulation
Arguments:
string regex - Command to run for each string, where every instance of "%n" will be replaced with the thread number.
string num - Thread number
Referenced by main().
Variable Documentation
mutex printing
To prevent multiple threads from using stdout at the same time.
Referenced by runSimRegex().